file.close()
file=open("C:\\in\\testing.txt",'r')
file=open("C:\\in\\testing.txt",'w')
file.close()
a=file.read()
a
a=file.read()
content=file.read()
print(content)

##---(Sun Mar 15 16:45:06 2015)---
file=open("C:\\in\\testing.txt",'w')
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Such a nice file that I am!")
file=open("C:\\in\\testing.txt",'r')
content=file.read()
print(content)
file.close()

##---(Mon Mar 16 10:16:13 2015)---
file=open("C:\\in\\testing.txt",'w')
file.close()
del file
file=open("C:\\in\\testing.txt",'w')
file.write("\nNice File")
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Sice File\n")
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Cice File\n")
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Cice File\n")
file.close()
file.write("Cice File\n")
file=open("C:\\in\\testing.txt",'w')
file.write("Cice File\n")
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Cice File")
file.write("Nice File")
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Such a Nice File")
file.close()
file=open("C:\\in\\testing.txt",'wb')
file.write("Such a Nice File")
file.writelines("Such a Nice File")
file.write_lines("Such a Nice File")
file.writelines("Such a Nice File")
file=open("C:\\in\\testing.txt",'a')
file.write("Such a Nice File")
file.close()
file=open("C:\\in\\testing.txt",'a')
file.write("Such a Nice Fileeee")
file.close()
file=open("C:\\in\\testing.txt",'a')
file.write("\nSuch a Nice Fileeee")
file.close()
file=open("C:\\in\\testing.txt",'w')
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("Such a nice file that I am!")
file=open("C:\\in\\testing.txt",'r')
content=file.read()
print(content)
file.close()
file=open("C:\\in\\testing.txt",'w')
file.write("New line here!")
file.close()
file=open("C:\\in\\testing.txt",'a')
file.write("\nThis goes to the next line!")
file.close()
with open("C:\\in\\testing.txt",'w') as file:    file.write("Brand new method!")
import os
os.getcwd()
dir(os)
os.chdir("C:\\in")

##---(Mon Mar 16 13:32:48 2015)---
import os
os.getcwd()
dir(os)
os.chdir("C:\\in")
os.getcwd()
os.chdir("C:")

##---(Mon Mar 16 13:44:50 2015)---
import os
os.chdir("C:\\in")
os.chdir("..")
os.chdir("C:\\in")
os.chdir("C:\\")
os.getcwd()
os.chdir("C:\\in")
os.chdir("C:")
os.getcwd()
import os
os.getcwd()
dir(os)
os.chdir("C:\\in")
os.getcwd()
os.chdir("C:\\")
os.makedirs("C:\\in")
with open("testing.txt",'w') as file:    file.write("Fresh directory!")    
import os
os.getcwd()
dir(os)
os.chdir("C:\\in")
os.getcwd()
os.chdir("C:\\")
os.makedirs("C:\\in")
os.chdir("C:\\in")
with open("testing.txt",'w') as file:
    file.write("Fresh directory!")
os.listdir()
os.remove("testing.txt")
os.listdir()